output "cluster_endpoint" {
  description = "Talos cluster endpoint URL used for machine configuration generation."
  value       = local.cluster_endpoint
}

output "talosconfig" {
  description = "Generated talosconfig."
  value       = data.talos_client_configuration.this.talos_config
  sensitive   = true
}

output "kubeconfig" {
  description = "Generated kubeconfig with optionally rewritten server host."
  value       = local.kubeconfig
  sensitive   = true
}

output "kubeconfig_data" {
  description = "Structured kubeconfig values for other providers."
  value       = local.kubeconfig_data
  sensitive   = true
}

output "client_configuration" {
  description = "Talos client configuration generated by talos_machine_secrets."
  value       = talos_machine_secrets.this.client_configuration
  sensitive   = true
}

output "machine_secrets" {
  description = "Talos machine secrets generated by talos_machine_secrets."
  value       = talos_machine_secrets.this.machine_secrets
  sensitive   = true
}

output "control_plane_machine_configurations" {
  description = "Generated machine configurations for control-plane nodes."
  value       = data.talos_machine_configuration.control_plane
  sensitive   = true
}

output "worker_machine_configurations" {
  description = "Generated machine configurations for worker nodes."
  value       = data.talos_machine_configuration.worker
  sensitive   = true
}
